import Link from 'next/link';
import { getRandom } from '../lib/util';
import './globals.css';

export const revalidate = 1;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div>layout random: {getRandom()}</div>
        <nav style={{ display: 'flex', gap: '1rem' }}>
          <Link href={'/'}>Home</Link>
          <Link href={'/test'}>Test</Link>
          <Link href={'/otherroute'}>Other Route</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
